### ISSUE TITLE
Ragarding your Understanding Jargon article

### ISSUE THREAD

**Issue by Aprilahhhh** [jeffhj/CDM#1]
Hello, my name is Yang Liu. I am a student of Beijing Language and Culture University, major in computer science, and I’m interested in text generation. Your work gave me a lot of inspiration. I am wondering if you could kindly send me the dataset and the source code about your atricle（blcu.liuyang22@gmail.com）. I promise they will be used only for research purposed and all subsequent research will reference yours.

Appreciate your help :) !

**Comment by jeffhj** [comment]
Hi Yang, I should have sent the code and data to you on 7.4 with my university email (please let me know whether you received it, so I can have a better understanding of how our university email works :). I resent the code and data to you with my Gmail.

**Comment by Aprilahhhh** [comment]
Hi Jie，Thanks for your reply !!! I have received what I need from you Gmail.
I double checked my mail inbox and I'm sorry that I didn't receive any mail from your university email. There may be some problems with sending emails between the education mailbox and the gmail mailbox.
