### ISSUE TITLE
Package Dependencies?

### ISSUE THREAD

**Issue by hassamalhajaji** [jeffhj/CDM#2]
Hi,

Could you share the package dependencies for the extraction and generation?

**Comment by jeffhj** [comment]
Hi @hassamalhajaji,

For the extraction process, you may check the script you want to run to see what packages are being used. Common package dependencies should generally be compatible and function as expected.

Regarding the generation process, you can refer to the `generation/requirements.txt` file for a list of required packages and dependencies.

**Comment by hassamalhajaji** [comment]
Thank you! I only ask because in the extraction classifier.py you use torchtext packages that are a part of the legacy functionality but are no longer available.

https://github.com/pytorch/text/tree/master/torchtext/legacy

For functions like Field, TabularDataset, BucketIterator, and Iterator, what are my alternatives?

**Comment by jeffhj** [comment]
If that is the case, you could consider using earlier versions of the packages. Unfortunately, I cannot recall the exact version we used previously lol

**Comment by jeffhj** [comment]
Let me know if you still have trouble running it. When I have time, I can try to find the version that could work.

**Comment by hassamalhajaji** [comment]
I looks like legacy has been taken off since torchtext version 0.8.0. These seem compatible and working for me so far:

torchtext 0.6.0
pytorch 1.11.0
scikit-learn 1.2.2

Thank you very much @jeffhj
